[package]
name = "multiblox"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]
trayicon = "0.1.3"
winapi = { version = "0.3.9", features = ["winuser"] }
